//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicationServices.Helpers.TextResorce {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUserMsm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUserMsm() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplicationServices.Helpers.TextResorce.ResourceUserMsm", typeof(ResourceUserMsm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales Invalidas.
        /// </summary>
        internal static string CredentialsInvalidate {
            get {
                return ResourceManager.GetString("CredentialsInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha no debe ser menor a la fecha actual.
        /// </summary>
        internal static string InvalidCreationDateDto {
            get {
                return ResourceManager.GetString("InvalidCreationDateDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parametro DescriptionDto es invalido..
        /// </summary>
        internal static string InvalidDescriptionDto {
            get {
                return ResourceManager.GetString("InvalidDescriptionDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro no es válido.
        /// </summary>
        internal static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Invalido.
        /// </summary>
        internal static string InvalidValueString {
            get {
                return ResourceManager.GetString("InvalidValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros.
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a paciente ya existe, valide por favor..
        /// </summary>
        internal static string NotExistPatient {
            get {
                return ResourceManager.GetString("NotExistPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario No existe, valide por favor..
        /// </summary>
        internal static string NotExistUser {
            get {
                return ResourceManager.GetString("NotExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no es valida..
        /// </summary>
        internal static string PasswordNotExist {
            get {
                return ResourceManager.GetString("PasswordNotExist", resourceCulture);
            }
        }
    }
}
